version: '3.9'
services:
  app:
    container_name: task-management-api
    image: node:18
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run migrate:deploy && npm run build && npm start"
    restart: always
    volumes:
      - ./package.json:/usr/src/app/package.json:z
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: task-management-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:
    driver: local